### PR TITLE
Uncomment tests

### PR DESCRIPTION
**Pull request by iankronquist**
The developers need to do a better job reviewing each others' code. Commented out tests were merged into develop. Afterwards there was a regression which was not detected by the tests. I think that the developers should take a moment to reflect on why this mistake happened and what steps can be taken, automatically or manually, to prevent its recurrence.

### CODE REVIEW

**Comment by tschuy** [comment]
Pull request we screwed up: https://github.com/osuosl/timesync-node/pull/110

That was me and @Kennric that OK'd that.

**Comment by tschuy** [comment]
My guess is that I OK'd the tests, and then OK'd the ``src/`` without re-OKing the tests.

**Comment by tschuy** [comment]
@Kennric @matthewrsj @MaraJade This PR should be reviewed and merged.

**Comment by Kennric** [comment]
This looks correct, lets get another review and get it merged as soon as we can

**Comment by tschuy** [comment]
+1

**Pull request merged**
