### PR TITLE
Enhance tests

### PR DESCRIPTION
**Pull request by tschuy**
```
=============================== Coverage summary ===============================
Statements   : 75.39% ( 144/191 )
Branches     : 67.31% ( 35/52 )
Functions    : 58.82% ( 30/51 )
Lines        : 75.39% ( 144/191 )
================================================================================
```

It's better!

### CODE REVIEW

**Comment by iankronquist** [comment]
We need to put code coverage under CI.

**Comment by ElijahCaine** [comment]
Tests pass. You got rid of a lot of code, I know routes and users were going to be deprecated eventually. Are we sure this is the right time to do so?

**Comment by tschuy** [comment]
Might as well get rid of them now. It's not like they're serving any purpose, and they're not even useful examples of tests.

**Comment by ElijahCaine** [comment]
Sounds good to me. You have caught a wild +1. Congrats.

**Comment by iankronquist** [comment]
Looks good, but you need to fix the merge conflicts.

**Pull request merged**
