### PR TITLE
Add the users endpoint

### LINKED ISSUE #237: [8] Tests for user endpoint
The new /users endpoint will need GET, POST, and DELETE tests.

### PR DESCRIPTION
**Pull request by LyonesGamer**
Fixes #237 and #238.

### CODE REVIEW

**Comment by Kennric** [comment]
Let's rename those perms to something like site_admin, site_manager, site_spectator

**Comment by ElijahCaine** [comment]
Tests look good, I'll get started on the implementation.

**Comment by ElijahCaine** [comment]
Tests pass, so *I* think it looks good. I wrote the implementation so we should get two people to review this who are not @LyonesGamer and myself.

**Comment by Kennric** [comment]
I'm happy with this, a second opinion is always a good idea. +1

**Comment by Kennric** [comment]
Looking pretty good. +1

**Comment by athai** [comment]
Code looks good to me, but one of the Travis tests is failing.

**Pull request merged**
