### PR TITLE
use transactions for multi-query endpoints

### PR DESCRIPTION
**Pull request by tschuy**

### CODE REVIEW

**Comment by Kennric** [comment]
I don't see any issues, please get a second opinion. +1

**Comment by ElijahCaine** [comment]
I will give this a plus one once there are more comments added.

Transactions aren't something most of us thoroughly understand so a bit of context before the additions saying 'This is what this block accomplishes' or something to that extent would be useful.

Otherwise it looks great (``209 passing (7s)`` is my favorite part)

**Comment by tschuy** [comment]
@Kennric @ElijahCaine updated with comments.

**Comment by ElijahCaine** [comment]
I like it. +1

**Comment by tschuy** [comment]
``10:29:01  kennric | tschuy: you can go ahead and merge timesync #192``

**Pull request merged**
