### PR TITLE
Add Istanbul test coverage tracker

### PR DESCRIPTION
**Pull request by iankronquist**
Istanbul skyline

```
(timesync)iankronquist@puppettop:(timesync)(ian/istanbul-sokaklari) → npm run coverage

> timesync@0.0.0 coverage /Users/iankronquist/gg/timesync
> export DATABASE=mocha export PORT=8851 && rm -f test.sqlite3 && knex --env mocha migrate:latest && istanbul cover _mocha -- tests

Using environment: mocha
Batch 1 run: 1 migrations 
/Users/iankronquist/gg/timesync/migrations/20150101000000_00.js


App now listening on 8851
  Endpoints
    GET /times
      ✓ should return all times in the database
    GET /times/:id
      ✓ should return times by id
      ✓ should fail with Object not found error
    GET /users
      ✓ should return all users in the database
    GET /activities
      ✓ should return all activities in the database
    GET /activities/:slug
      ✓ should return activities by slug
      ✓ should fail with invalid slug error
    GET /projects
      ✓ should return all projects in the database
    GET /projects/:slug
      ✓ should return projects by slug
      ✓ should fail with invalid slug error


  10 passing (460ms)

=============================================================================
Writing coverage object [/Users/iankronquist/gg/timesync/coverage/coverage.json]
Writing coverage reports at [/Users/iankronquist/gg/timesync/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 89.22% ( 149/167 )
Branches     : 63.16% ( 24/38 )
Functions    : 79.07% ( 34/43 )
Lines        : 89.22% ( 149/167 )
================================================================================

```

### CODE REVIEW

**Comment by iankronquist** [comment]
Crap, that's on the wrong branch.

**Comment by iankronquist** [comment]
I would add code climate integration too but I can't generate a repo token: http://docs.travis-ci.com/user/code-climate/#JavaScript

**Comment by tschuy** [comment]
Please add docs about running this.

**Comment by tschuy** [comment]
I can confirm this works, though for some reason I had to manually install Istanbul even though I'd run ``npm install``:

coverage

:+1: We can deal with code climate in a separate PR.

**Comment by tschuy** [comment]
For Code Climate, I'd rather do PR integration than Travis integration. I pinged kennric with a link about setting that up.

**Comment by iankronquist** [comment]
@tschuy docs added. I blew away my node modules and reinstalled and it was installed properly for me.

**Comment by tschuy** [comment]
Is there any reason to not make this the default test runner (like we get coverage reports when running unit tests for python-webapp)?

**Comment by iankronquist** [comment]
Well the test command grows longer and more horrible than it already is. I can if you'd like.

**Comment by tschuy** [comment]
I think it's worth having. No reason not to, IMHO. The test command is already gross.

**Comment by tschuy** [comment]
Looks like what you mentioned on irc won't be possible, returning mocha's status code. We could either add that to istanbul, or just keep them separate. For now, I'll keep them separate; making it return the proper status code can be for another time.

**Comment by Kennric** [comment]
Looks good to me. +1

**Pull request merged**
