### PR TITLE
New query error

### PR DESCRIPTION
**Pull request by athai**
The query string tests have a new error to check against.

https://github.com/osuosl/timesync-node/blob/tristan/query-string-tests/tests/times.js#L118

### CODE REVIEW

**Comment by tschuy** [comment]
Can you also make a PR to osuosl/timesync?

**Comment by athai** [comment]
To update the error docs?

**Comment by tschuy** [comment]
Yeah

**Comment by athai** [comment]
Tristan already updated the docs! :smile:  https://github.com/osuosl/timesync/blob/develop/source/draft_errors.rst#bad-query-value

**Comment by tschuy** [comment]
can you update this to match the docs? (And his tests?)

**Comment by tschuy** [comment]
which is basically getting rid of the quotes.

**Comment by athai** [comment]
His tests have double quotes around the values though... so should I update the docs to include them? Or take them out of the tests?

**Comment by tschuy** [comment]
take them out of the tests.

**Comment by tschuy** [comment]
This looks good to me. I think it might be best if people fix the tests for the ones they're implementing individually.

**Comment by Kennric** [comment]
This looks good to me. +1

**Pull request merged**
