### PR TITLE
add clear-database command

### PR DESCRIPTION
**Pull request by tschuy**
Once we get a testing env up for docker, I'll redo this a little to clear postgres as well.

### CODE REVIEW

**Comment by Kennric** [comment]
Not the most elegant thing in the world, but appears to do the job. +1

**Comment by iankronquist** [comment]
Since we are using transactions in tests and no longer using the Great Pyramid of TimeSync this code will not be duplicated and it has my +1.

**Comment by tschuy** [comment]
I've updated this. It now doesn't set the indexes, since that's database-specific and not really needed for a dev env. It does however output whenever there's an error what exactly that error is!

**Comment by LyonesGamer** [comment]
Looks good to me. +1

**Comment by tschuy** [comment]
```
10:31:09   tschuy | kennric: what about #164>
10:33:48  kennric | tschuy: yes
```

**Pull request merged**
