### PR TITLE
Fixed order of build instructions in README

### LINKED ISSUE #273: `npm run create-account` gives error
@LyonesGamer I am trying to set up timesync-node on a new machine (as I am having some issues with the old one), `npm install` worked fine, then when I try to do `npm run create-account` it gives me the following error -

```
~/D/timesync-node (develop) $ npm run create-account

> timesync@0.1.0 create-account /Users/chaitanyagupta/Desktop/timesync-node
> node --harmony ./scripts/create-account.js

Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Unhandled rejection Error: select "id" from "users" - SQLITE_ERROR: no such table: users
    at Error (native)
```

What am I doing wrong?

### PR DESCRIPTION
**Pull request by iCHAIT**
fixes #273.

### CODE REVIEW

**Comment by LyonesGamer** [comment]
+1

**Comment by ElijahCaine** [comment]
@iCHAIT++ for README fixes. +1

**Comment by Kennric** [comment]
+1

**Pull request merged**
