### PR TITLE
Add UUIDs and Revision numbers

### LINKED ISSUE #183: Give objects UUIDs and revisions, make times immutable.
Follows up on #170, times could not be implemented properly due to being referenced by IDs. The schema changes necessary will also prepare us to implement the data structure changes for https://github.com/osuosl/timesync/issues/30. May also supersede parts of #173.

### PR DESCRIPTION
**Pull request by LyonesGamer**
Fixes #183. Adds UUID and Revision numbers to all objects.

### CODE REVIEW

**Comment by LyonesGamer** [comment]
Implementation has now been added.

**Comment by LyonesGamer** [comment]
Rebased to develop.

**Comment by ElijahCaine** [comment]
I did a quick read-through of this PR. Everything looks good and the tests still pass. I'll give it a  +1. Good job.

**Comment by Kennric** [comment]
+1

**Pull request merged**
