### PR TITLE
add production database environment

### PR DESCRIPTION
**Pull request by tschuy**
This required updating the fixtures as well, since many of them took
advantage of sqlite being lazy and allowing bad foreign keys.

It also moves everything over to the NODE_ENV variable, which is the
"blessed" way of doing this kind of config.

### CODE REVIEW

**Comment by tschuy** [comment]
the environment variable ``PG_CONNECTION_STRING`` should be set to a string like ``postgres://username:password@server:port/table_name``.

**Comment by LyonesGamer** [comment]
Add some small documentation regarding PG_CONNECTION_STRING and it should be good.

**Comment by LyonesGamer** [comment]
+1

**Comment by Kennric** [comment]
I don't see any issues. +1

**Pull request merged**
