### PR TITLE
Dockerize TimeSync

### PR DESCRIPTION
**Pull request by iankronquist**
~~This isn't quite ready -- the postgres container is behaving strangely.~~

### CODE REVIEW

**Comment by ElijahCaine** [comment]
This is duplicating effort from #175.

**Comment by iankronquist** [comment]
This is more complete than #175. This includes a Dockerfile for the webapp, and you told me your PR does not. I did not want to branch off #175 because such dependencies get messy.

**Comment by iankronquist** [comment]
@osuosl/devs This is ready for review. Please ensure that my instructions work on the workstations. If they are unclear or you encounter errors please let me know.

**Comment by ElijahCaine** [comment]
@iankronquist I took a look at this and tried following the instructions listed but encountered an error when attempting to run ``npm run migrations`` after starting the postgres container and exporting the ``PG_CONNECTION_STRING`` and ``NODE_ENV`` variables:
```
 $ npm run migrations

> timesync@0.0.0 migrations /path/to/timesync-node
> knex migrate:latest

Using environment: production
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: database "timesync-prod" does not exist
Knex:Error Pool2 - error: database "timesync-prod" does not exist
Error: Pool was destroyed
    at Pool._destroyPool (/path/to/timesync-node/node_modules/knex/node_modules/pool2/lib/pool.js:536:20)
    at Pool.<anonymous> (/path/to/timesync-node/node_modules/knex/node_modules/pool2/lib/pool.js:458:18)
    at Pool.<anonymous> (/path/to/timesync-node/node_modules/knex/node_modules/pool2/lib/pool.js:493:17)
    at tryCatcher (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "migrations"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! timesync@0.0.0 migrations: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the timesync@0.0.0 migrations script 'knex migrate:latest'.
npm ERR! This is most likely a problem with the timesync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex migrate:latest
npm ERR! You can get their info via:
npm ERR!     npm owner ls timesync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/timesync-node/npm-debug.log
```
I was following the instructions character for character, so there seems to be a step missing or there needs to be a 'before you start' note.

**Comment by ElijahCaine** [comment]
@iankronquist I took a look at this and tried following the instructions listed but encountered an error when attempting to run ``npm run migrations`` after starting the postgres container and exporting the ``PG_CONNECTION_STRING`` and ``NODE_ENV`` variables:
```
 $ npm run migrations

> timesync@0.0.0 migrations /path/to/timesync-node
> knex migrate:latest

Using environment: production
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: database "timesync-prod" does not exist
Knex:Error Pool2 - error: database "timesync-prod" does not exist
Error: Pool was destroyed
    at Pool._destroyPool (/path/to/timesync-node/node_modules/knex/node_modules/pool2/lib/pool.js:536:20)
    at Pool.<anonymous> (/path/to/timesync-node/node_modules/knex/node_modules/pool2/lib/pool.js:458:18)
    at Pool.<anonymous> (/path/to/timesync-node/node_modules/knex/node_modules/pool2/lib/pool.js:493:17)
    at tryCatcher (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/path/to/timesync-node/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "migrations"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! timesync@0.0.0 migrations: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the timesync@0.0.0 migrations script 'knex migrate:latest'.
npm ERR! This is most likely a problem with the timesync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex migrate:latest
npm ERR! You can get their info via:
npm ERR!     npm owner ls timesync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/timesync-node/npm-debug.log
```
I was following the instructions character for character, so there seems to be a step missing or there needs to be a 'before you start' note.

**Comment by iankronquist** [comment]
Oh, it looks like I forgot to document the `createdb` step.

**Comment by iankronquist** [comment]
@tschuy Hey, this looks like it's ready to go. Can you review it?

**Pull request closed without merging**
