### PR TITLE
De-duplicated insert/update code and make objects immutable

### LINKED ISSUE #170: [21] De-duplicate code + make objects immutable
This is a two-part issue:

1. There is a lot of duplicate code surrounding our create and update code. We need to try to coalesce our code into reusable functions, so that changes to this system can be more easily implemented.

2. Objects are now immutable, except for a ``deleted_at`` field. When an object is updated, whether soft-deleted or not, a new, duplicate object is created (with the changes made by the update), and pointed via ``parent`` field to the previous object. This creates an audit trail. ``created_at`` will be carried over from object instance to instance, remaining constant, while ``updated_at`` will be the time that that instance of the object was created (i.e. that row in the database).

### PR DESCRIPTION
**Pull request by LyonesGamer**
Fixes #170.

### CODE REVIEW

**Comment by LyonesGamer** [comment]
Blocked on code for #171.

**Comment by LyonesGamer** [comment]
Blocked code is in #176.

**Comment by LyonesGamer** [comment]
As mentioned in #170, this code is as complete as it can be until #183 is implemented. This branch is *not* ready to merge because times remain broken, but a PR for #183 will be merged off of this branch, so it would be best to get this branch reviewed in preparation for that PR.

**Comment by LyonesGamer** [comment]
#185 is significantly different than this branch, and achieves many/most of the goals present in this PR, and therefore fully supersedes this. It also is branched off of develop. For these reasons, this PR will be closed, and its issue will now point to #185.

**Comment by LyonesGamer** [comment]
Rebased to newest changes. Now uses transactions (and gets a very nice 7s for tests). Tests and linter pass.

**Comment by Kennric** [comment]
This is looking pretty good to me. +1

**Comment by ElijahCaine** [comment]
Tests pass, everything looks good to me. :+1:

**Pull request merged**
