### PR TITLE
Add delete failure to list of errors

### PR DESCRIPTION
**Pull request by athai**
Error to return upon a refusal of a delete request.

### CODE REVIEW

**Comment by tschuy** [comment]
``project is associated with time`` seems like a very opaque error. Perhaps ``project has associated times``?

**Comment by tschuy** [comment]
Looks good. Vague, but I suppose we can't really do better if we want it to be generic. @Kennric

**Comment by Kennric** [comment]
Maybe too vague? Ideally, we would like to say something like "Method DELETE not allowed for activity: coding has times associated.", but this might be complicated by using the same error for things caught at the express level vs the endpoint code level.

Also, at what point are we setting the requisite "Allow" header?

**Comment by ElijahCaine** [comment]
This matches up with osuosl/timesync#20 and I agree with that. Let's make sure we merge osuosl/timesync#20 as well. (update the docs -> update the code)

**Comment by tschuy** [comment]
I merged osuosl/timesync#20, so this is good to go whenever.

**Comment by tschuy** [comment]
Looks good to me.

**Comment by Kennric** [comment]
Matches the current API spec - at some point I'd liek to make this a bit more sophisticated, but this is good to go for now. +1

**Pull request merged**
